/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce } from 'three';

function Model4({
    animation,
    ...props
}) {
    const { nodes, materials, animations } = useGLTF('/models/ALL ANIMATIONS.glb') //animations: NOD_YES, SHAKE_NO, HEAD_TILT, EMBARRASSED
    const group = useRef();
    const { actions, mixer } = useAnimations(animations, group);
    useEffect(() => {
          // Make sure the animations are there before trying to play them / fade out
          if (!actions || !actions[animation]) {
            console.warn("Animation action not ready yet"); 
            return;
        }

        let curAnimation = actions[animation];
        curAnimation.setLoop(LoopOnce);
        curAnimation.clampWhenFinished = true;
        curAnimation.enabled = true;
        curAnimation.play();
        
        return () => {
            if (actions[animation]) {
                actions[animation].fadeOut(0.1);
                actions[animation].stop();
                actions[animation].reset();
            }
        }
      
    }, [animation]);


      return (
    <group scale={100} position={[0, -4, 0]} ref={group} {...props} dispose={null}>
        <group name="Scene">
            <group name="DANCE_-_main" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body} />
            </group>
            <group name="EMBARRASSED" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body_1} />
            </group>
            <group name="HEAD_TILT" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body_2} />
            </group>
            <group name="SHAKE_NO" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body_3} />
            </group>
            <group name="NOD_YES" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body_4} />
            </group>
        </group>
    </group>
  )
}

useGLTF.preload('/models/ALL ANIMATIONS.glb')

export default Model4;