/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce, LoopPingPong } from 'three';

export default function Model({
    animation,
    animCount,
    ...props
}) {
    const { nodes, animations } = useGLTF('/models/Buddy_Robot.glb') //animations: DANCE, NOD YES, SHAKE NO, HEAD TILT, EMBARRASSED
    const group = useRef();
    const { actions, mixer } = useAnimations(animations, group);

    useEffect(() => {
        if (!actions || !animation) return;

        Object.values(actions).forEach((a) => a.stop());
        const action = actions[animation];
        if (!action) return;

        action.reset();
        action.setLoop(LoopOnce, 1);
        action.clampWhenFinished = true;
        action.fadeIn(0.3).play();

        const handleFinish = () => {
            console.log("Animation finished:", animation);
        };

        mixer.addEventListener("finished", handleFinish);
        return () => mixer.removeEventListener("finished", handleFinish);
    }, [animation, animCount, actions]);


      return (
    <group scale={100} position={[0, -4, 0]} ref={group} {...props} dispose={null}>
        <group name="Scene">
            <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body} />
            </group>
        </group>
    </group>
  )
}

useGLTF.preload('/models/Buddy_Robot.glb')