/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce, LoopPingPong } from 'three';

export default function Model({
    animation,
    ...props
}) {
    const { nodes, materials, animations } = useGLTF('/models/Buddy_Robot.glb') //animations: DANCE NOD_YES, SHAKE_NO, HEAD_TILT, EMBARRASSED
    const group = useRef();
    const { actions, mixer } = useAnimations(animations, group);
    useEffect(() => {
          // Make sure the animations are there before trying to play them / fade out
          if (!actions || !actions[animation]) {
            console.warn("Animation action not ready yet"); 
            return;
        }

        let curAnimation = actions[animation];
        curAnimation.setLoop(LoopPingPong, Infinity);
        curAnimation.clampWhenFinished = true;
        curAnimation.enabled = true;
        curAnimation.play();
        
        return () => {
            if (actions[animation]) {
                actions[animation].fadeOut(0.1);
                actions[animation].stop();
                actions[animation].reset();
            }
        }
      
    }, [animation]);


      return (
    <group scale={100} position={[0, -4, 0]} ref={group} {...props} dispose={null}>
        <group name="Scene">
            <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                <primitive object={nodes.bone_body} />
            </group>
        </group>
    </group>
  )
}

useGLTF.preload('/models/Buddy_Robot.glb')