/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { LoopOnce } from 'three';

function Model3({
    animation,
    ...props
}) {
    const { nodes, materials, animations } = useGLTF('/models/nodding_shaking.glb')
    const group = useRef();
    const { actions, mixer } = useAnimations(animations, group);

    useEffect(() => {
          // Make sure the animations are there before trying to play them / fade out
          if (!actions || !actions[animation]) {
            console.warn("Animation action not ready yet"); 
            return;
        }

        let curAnimation = actions[animation];
        curAnimation.setLoop(LoopOnce);
        curAnimation.clampWhenFinished = true;
        curAnimation.enable = true;
        curAnimation.play();
        
        return () => {
            if (actions[animation]) {
                actions[animation].fadeOut(0.1);
                actions[animation].stop();
                actions[animation].reset();
            }
        }
      
    }, [animation]);


    return (
        <group scale={100} position={[0, -4, 0]} ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group
                name="MAIN_RIG"
                rotation={[Math.PI / 2, 0, 0]}
                scale={0.01}
                userData={{ name: 'MAIN RIG' }}>
                <primitive object={nodes.bone_body} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/nodding_shaking.glb')

export default Model3;