# ====================================================================
# Three Services
# ====================================================================
#  1) Database (postgres)
#  2) Backend  (websocket server, LLM calls, biomarker logic)
#  3) Frontend (vite, react) 
services:
  # -------------------------------------------------------------------- 
  # 1) Database
  # --------------------------------------------------------------------
  # Backend/Database are only accessable inside the Docker network.
  db:
    image: postgres 
    container_name: db
    env_file: 
      - .env
      - .env.deploy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
  
  # --------------------------------------------------------------------
  # 2) Backend (private, no ports exposed)
  # --------------------------------------------------------------------
  # Nginx/Vite proxies traffic here using the container name over the Docker network
  backend:
    build:
      context: ./backend
      dockerfile: ${BACKEND_DOCKERFILE}  # Dockerfile-backend
    container_name: backend
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    volumes:
      - ./backend:/app                          # general project mount
      - ../deployment-files/logs:/app/logs      # log folder mounted separately
      - ../deployment-files/wheels:/app/wheels  # wheels folder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    env_file: 
      - .env
      - .env.deploy
    environment:
      - TZ=UTC
    depends_on:
      - db
    networks:
      - appnet

  # --------------------------------------------------------------------
  # 3) Frontend
  # --------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    container_name: frontend
    depends_on:
      - backend
    env_file: 
      - .env
      - .env.deploy
    environment:
      - TZ=UTC
    ports:
      - "5173:5173"
    networks:
      - appnet

# ====================================================================
# Volumes & Networks
# ====================================================================
volumes:
  postgres_data:

networks:
  appnet:
