# ====================================================================
# Three Services
# ====================================================================
#  1) Database (postgres)
#  2) Llama API
#  3) Backend  (websocket server, LLM calls, biomarker logic)
#  4) Frontend (vite, react) 
services:
  # -------------------------------------------------------------------- 
  # 1) Database
  # --------------------------------------------------------------------
  # Backend/Database are only accessable inside the Docker network.
  db:
    image: postgres 
    container_name: db
    env_file: 
      - .env
      - .env.deploy
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      #- POSTGRES_USER=${POSTGRES_USER}
      #- POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TZ=UTC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet

  # -------------------------------------------------------------------- 
  # 2) Llama API (included)  
  # --------------------------------------------------------------------
  # Could probably share more between the two compose files and put it here (port, network, volumes, etc.)
  llama_api:
    extends:
      file: ${LLM_COMPOSE_FILE}
      service: llama_api
    volumes:
      - ../deployment-files/models:/models
      - ./llama_api:/config


  # --------------------------------------------------------------------
  # 3) Backend (private, no ports exposed)
  # --------------------------------------------------------------------
  # Nginx/Vite proxies traffic here using the container name over the Docker network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile-backend
    container_name: backend
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py seed_demo &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    volumes:
      - ./backend:/app                          # general project mount
      - ../deployment-files/logs:/app/logs      # log folder mounted separately
    env_file: 
      - .env
      - .env.deploy
    environment:
      - TZ=UTC
    depends_on:
      - db
      - llama_api
    networks:
      - appnet

  # --------------------------------------------------------------------
  # 4) Frontend
  # --------------------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-frontend
    container_name: frontend
    depends_on:
      - backend
    env_file: 
      - .env
      - .env.deploy
    environment:
      - TZ=UTC
    ports:
      - "5173:5173"
    networks:
      - appnet

# ====================================================================
# Volumes & Networks
# ====================================================================
volumes:
  postgres_data:

networks:
  appnet:
