# ====================================================================
# Volumes & Networks
# ====================================================================
# Single definition of shared infrastructure
volumes:
  db_data:
  letsencrypt:
  webroot:

networks:
  appnet:

# ====================================================================
# Services
# ====================================================================
services:
  # -------------------------------------------------------------------- 
  # 1) Database (postgres)
  # --------------------------------------------------------------------
  db:
    extends: { file: ./backend/docker-compose.backend.yaml, service: db }
    networks: [appnet]

  # --------------------------------------------------------------------
  # 2) Backend (websocket server, LLM calls, biomarker logic)
  # --------------------------------------------------------------------
  # Nginx/Vite proxies traffic here using the container name over the Docker network
  backend:
    extends: { file: ./backend/docker-compose.backend.yaml, service: backend }
    networks: [appnet]
    depends_on: [llama_api]
    env_file: [./.env]      # optional global override

  # --------------------------------------------------------------------
  # 3) Frontend (vite, react) 
  # --------------------------------------------------------------------
  frontend:
    extends: { file: ./frontend/docker-compose.frontend.yaml, service: frontend }
    networks: [appnet]
    env_file: [./.env]

  # -------------------------------------------------------------------- 
  # 4) Llama API
  # --------------------------------------------------------------------
  # Could probably share more between the two compose files and put it here (port, network, volumes, etc.)
  llama_api:
    extends:
      file: ${LLM_COMPOSE_FILE}
      service: llama_api
    volumes:
      - ../deployment-files/models:/models
      - ./llama_api:/config

  # --------------------------------------------------------------------
  # 5) Proxy with Nginx & Certbot
  # --------------------------------------------------------------------
  nginx:
    extends: { file: ./nginx/docker-compose.proxy.yaml, service: nginx }
    networks: [appnet]
    env_file: [./.env]

  certbot:
    extends: { file: ./nginx/docker-compose.proxy.yaml, service: certbot }
    networks: [appnet]
    env_file: [./.env]
