# ====================================================================
# Backend Services (Postgres database & Django server)
# ====================================================================
services:
  # -------------------------------------------------------------------- 
  # 1) Postgres Database
  # --------------------------------------------------------------------
  # Database is only accessable through the backend Django server
  db:
    image: postgres
    container_name: db
    env_file: [.env]
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [appnet]

  # -------------------------------------------------------------------- 
  # 2) Django Backend Server
  # --------------------------------------------------------------------
  # Database is only accessable through the backend Django server
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    container_name: backend
    command: |
      sh -c "
        python manage.py makemigrations --noinput &&
        python manage.py migrate --noinput &&
        python manage.py seed_demo &&
        daphne -b 0.0.0.0 -p 8000 backend.asgi:application
      "
    env_file: [.env]
    volumes:
      - .:/app                # general project mount
    depends_on: [db]
    networks: [appnet]
    ports:                    # expose 8000 to host for Vite
      - "8000:8000"

volumes:
  db_data:

networks:
  appnet:
